# Generated by Django 4.2.26 on 2025-11-12 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_gainsight_company_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GongMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gong_meeting_id', models.CharField(db_index=True, help_text='Unique Gong meeting/call ID', max_length=100, unique=True)),
                ('gong_call_id', models.CharField(blank=True, db_index=True, help_text='Alternative Gong call ID', max_length=100, null=True)),
                ('meeting_title', models.CharField(help_text='Meeting title from Gong', max_length=500)),
                ('meeting_date', models.DateTimeField(help_text='Meeting start date/time')),
                ('duration_seconds', models.IntegerField(help_text='Meeting duration in seconds', validators=[django.core.validators.MinValueValidator(0)])),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Meeting duration in minutes (calculated)', null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='outbound', help_text='Meeting direction', max_length=20)),
                ('participants', models.JSONField(blank=True, default=list, help_text='Array of participant objects from Gong')),
                ('participant_count', models.IntegerField(default=0, help_text='Number of participants', validators=[django.core.validators.MinValueValidator(0)])),
                ('meeting_summary', models.TextField(blank=True, help_text='Meeting summary from Gong')),
                ('meeting_transcript', models.TextField(blank=True, help_text='Full meeting transcript if available')),
                ('raw_meeting_data', models.JSONField(blank=True, default=dict, help_text='Complete raw Gong API response')),
                ('ai_insights', models.JSONField(blank=True, default=dict, help_text='AI-processed insights with categories')),
                ('ai_processed', models.BooleanField(default=False, help_text='Whether AI processing has been completed')),
                ('ai_processed_at', models.DateTimeField(blank=True, help_text='Timestamp when AI processing was completed', null=True)),
                ('overall_sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], help_text='Overall sentiment from AI analysis', max_length=20, null=True)),
                ('key_topics', models.JSONField(blank=True, default=list, help_text='Key topics extracted from meeting')),
                ('deal_name', models.CharField(blank=True, help_text='Associated deal name from Gong', max_length=255, null=True)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, help_text='Deal value if available', max_digits=15, null=True)),
                ('deal_stage', models.CharField(blank=True, help_text='Deal stage if available', max_length=100, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp from Gong')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Customer/Company this meeting belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gong_meetings', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Gong Meeting',
                'verbose_name_plural': 'Gong Meetings',
                'ordering': ['-meeting_date'],
                'indexes': [models.Index(fields=['company', '-meeting_date'], name='gong_gongme_company_142835_idx'), models.Index(fields=['gong_meeting_id'], name='gong_gongme_gong_me_0abff6_idx'), models.Index(fields=['ai_processed', '-meeting_date'], name='gong_gongme_ai_proc_a893ab_idx')],
            },
        ),
    ]
