# Generated by Django 4.2.26 on 2025-11-12 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_data', models.JSONField(default=dict, help_text='Complete raw API response from external system (Salesforce, Gainsight, etc.)')),
                ('extracted_fields', models.JSONField(blank=True, default=dict, help_text='Extracted important fields from raw_data for quick access (optional)')),
                ('api_version', models.CharField(blank=True, help_text="API version used (e.g., 'v58.0' for Salesforce)", max_length=50, null=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Metadata',
                'verbose_name_plural': 'Integration Metadata',
                'ordering': ['-last_synced_at'],
                'indexes': [models.Index(fields=['-last_synced_at'], name='integration_last_sy_78f720_idx')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SALESFORCE', 'Salesforce'), ('GAINSIGHT', 'Gainsight'), ('HUBSPOT', 'HubSpot'), ('ZENDESK', 'Zendesk'), ('INTERCOM', 'Intercom'), ('OTHER', 'Other')], db_index=True, help_text='Type of integration (Salesforce, Gainsight, etc.)', max_length=20)),
                ('external_id', models.CharField(db_index=True, help_text='External system ID (e.g., Salesforce Opportunity ID, Gainsight GSID)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connector is currently active')),
                ('connection_metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about this connection (e.g., sync frequency, last error)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company (Customer) this integration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='integration_connectors', to='customers.customer')),
                ('metadata', models.ForeignKey(help_text='Metadata record containing raw API response', on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='integrations.integrationmetadata')),
            ],
            options={
                'verbose_name': 'Integration Connector',
                'verbose_name_plural': 'Integration Connectors',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'type'], name='integration_company_2cd0fc_idx'), models.Index(fields=['type', 'external_id'], name='integration_type_a301b4_idx'), models.Index(fields=['company', '-created_at'], name='integration_company_430d94_idx')],
                'unique_together': {('company', 'type', 'external_id')},
            },
        ),
    ]
