# Generated by Django 4.2.26 on 2025-11-12 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_customer_last_salesforce_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesforce_id', models.CharField(db_index=True, help_text='Salesforce Opportunity ID (e.g., 0064V00001NhvGwQAJ)', max_length=18, unique=True)),
                ('opportunity_name', models.CharField(help_text='Full opportunity name from Salesforce', max_length=255)),
                ('account_name', models.CharField(help_text='Account name from Salesforce', max_length=255)),
                ('stage', models.CharField(choices=[('qualified', 'Qualified'), ('development', 'Development'), ('proposal', 'Proposal'), ('negotiating', 'Negotiating'), ('contracting', 'Contracting'), ('ready_to_close', 'Ready to Close'), ('closed_won', 'Closed Won'), ('closed_lost', 'Closed Lost')], help_text='Current sales stage', max_length=50)),
                ('probability', models.DecimalField(decimal_places=2, help_text='Probability percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('close_date', models.DateField(help_text='Expected close date')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Opportunity amount', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency_code', models.CharField(default='USD', help_text='Currency code (USD, EUR, etc.)', max_length=3)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Amount converted to USD', max_digits=15, null=True)),
                ('opportunity_csm', models.CharField(blank=True, help_text='Customer Success Manager assigned', max_length=255)),
                ('renewal_categories', models.CharField(blank=True, choices=[('verbal_commit', 'Verbal Commit (95%)'), ('leaning_our_way', 'Leaning our Way (65%)'), ('neutral', 'Neutral (50%)'), ('leaning_away', 'Leaning Away (35%)'), ('at_risk', 'At Risk (20%)')], help_text='Renewal category classification', max_length=50)),
                ('opportunity_type', models.CharField(choices=[('new_business', 'New Business'), ('renewal', 'Renewal'), ('upsell', 'Upsell'), ('cross_sell', 'Cross-Sell')], default='renewal', help_text='Type of opportunity', max_length=50)),
                ('opportunity_owner', models.CharField(blank=True, help_text='Salesforce opportunity owner/team', max_length=255)),
                ('lead_source', models.CharField(blank=True, help_text='Lead source', max_length=255)),
                ('closed_reason', models.CharField(blank=True, help_text='Reason for closure (if closed)', max_length=255)),
                ('priority', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Opportunity priority', max_length=20)),
                ('custom_agreement', models.BooleanField(default=False, help_text='Custom agreement flag')),
                ('cpq_auto_renew', models.BooleanField(default=False, help_text='CPQ auto-renewal enabled')),
                ('send_survey_to_buying_contact', models.BooleanField(default=False, help_text='Send survey to buying contact')),
                ('billing_survey_sent_time', models.DateTimeField(blank=True, help_text='When billing survey was sent', null=True)),
                ('executive_influencers', models.TextField(blank=True, help_text='Executive influencers')),
                ('gr_number', models.CharField(blank=True, help_text='GR Number', max_length=100)),
                ('feature_request', models.TextField(blank=True, help_text='Feature requests')),
                ('furthest_stage', models.CharField(blank=True, help_text='Furthest stage reached', max_length=100)),
                ('was_lost_without_advancement', models.BooleanField(default=False, help_text='Was lost without advancement')),
                ('verbal_award', models.BooleanField(default=False, help_text='Verbal award milestone')),
                ('security_review_completed', models.BooleanField(default=False, help_text='Security review completed')),
                ('mutually_agreed_sign_date', models.BooleanField(default=False, help_text='Mutually agreed sign date')),
                ('financial_terms_agreed', models.BooleanField(default=False, help_text='Financial terms agreed')),
                ('legal_completed', models.BooleanField(default=False, help_text='Legal completed')),
                ('next_step', models.TextField(blank=True, help_text='Next step notes')),
                ('support_needed', models.TextField(blank=True, help_text='Support needed notes')),
                ('salesforce_metadata', models.JSONField(blank=True, default=dict, help_text='Additional Salesforce metadata (attributes, URLs, etc.)')),
                ('raw_api_response', models.JSONField(blank=True, default=dict, help_text='Complete raw API response from Salesforce for RAG processing')),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp from Salesforce')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesforce_opportunities', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Salesforce Opportunity',
                'verbose_name_plural': 'Salesforce Opportunities',
                'ordering': ['-close_date', '-amount'],
                'indexes': [models.Index(fields=['salesforce_id'], name='salesforce__salesfo_d8629b_idx'), models.Index(fields=['customer', '-close_date'], name='salesforce__custome_5ad475_idx'), models.Index(fields=['stage', '-amount'], name='salesforce__stage_3653bf_idx')],
            },
        ),
    ]
