# Generated by Django 4.2.26 on 2025-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='closed_reason',
            field=models.CharField(blank=True, help_text='Reason for closure (if closed)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='lead_source',
            field=models.CharField(blank=True, help_text='Lead source', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], help_text='Opportunity priority', max_length=20, null=True),
        ),
    ]
