# Generated by Django 4.2.26 on 2025-11-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0002_alter_salesforceopportunity_closed_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='executive_influencers',
            field=models.TextField(blank=True, help_text='Executive influencers', null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='feature_request',
            field=models.TextField(blank=True, help_text='Feature requests', null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='furthest_stage',
            field=models.CharField(blank=True, help_text='Furthest stage reached', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='gr_number',
            field=models.CharField(blank=True, help_text='GR Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='next_step',
            field=models.TextField(blank=True, help_text='Next step notes', null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='opportunity_csm',
            field=models.CharField(blank=True, help_text='Customer Success Manager assigned', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='opportunity_owner',
            field=models.CharField(blank=True, help_text='Salesforce opportunity owner/team', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='renewal_categories',
            field=models.CharField(blank=True, choices=[('verbal_commit', 'Verbal Commit (95%)'), ('leaning_our_way', 'Leaning our Way (65%)'), ('neutral', 'Neutral (50%)'), ('leaning_away', 'Leaning Away (35%)'), ('at_risk', 'At Risk (20%)')], help_text='Renewal category classification', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='support_needed',
            field=models.TextField(blank=True, help_text='Support needed notes', null=True),
        ),
    ]
