# Generated by Django 5.2.8 on 2025-11-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0003_alter_salesforceopportunity_executive_influencers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesforceopportunity',
            name='salesforce_id',
            field=models.CharField(db_index=True, help_text='Salesforce Opportunity ID (e.g., 0064V00001NhvGwQAJ)', max_length=255, unique=True),
        ),
    ]
