# Generated by Django 4.2.26 on 2025-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_salesforce_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful Salesforce sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesforce_account_id',
            field=models.CharField(blank=True, db_index=True, help_text='Salesforce Account ID for syncing', max_length=18),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesforce_synced',
            field=models.BooleanField(default=False, help_text='Whether customer data is synced from Salesforce'),
        ),
    ]
