# Generated by Django 4.2.26 on 2025-11-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_last_salesforce_sync_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gainsight_company_id',
            field=models.CharField(blank=True, db_index=True, help_text='Gainsight Company GSID for syncing', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='gainsight_synced',
            field=models.BooleanField(default=False, help_text='Whether customer data is synced from Gainsight'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_gainsight_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful Gainsight sync timestamp', null=True),
        ),
    ]
