# Generated by Django 5.2.8 on 2025-11-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gainsight_synced',
            field=models.BooleanField(default=False, help_text='Whether this customer has been synced from Gainsight'),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesforce_synced',
            field=models.BooleanField(default=False, help_text='Whether this customer has been synced from Salesforce'),
        ),
    ]
