# Generated by Django 5.2.8 on 2025-11-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_gainsight_synced_customer_salesforce_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gainsight_company_id',
            field=models.CharField(blank=True, help_text='Gainsight Company GSID', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_gainsight_sync',
            field=models.DateTimeField(blank=True, help_text='Last time synced from Gainsight', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_salesforce_sync',
            field=models.DateTimeField(blank=True, help_text='Last time synced from Salesforce', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='salesforce_account_id',
            field=models.CharField(blank=True, help_text='Salesforce Account ID', max_length=255, null=True),
        ),
    ]
