# Generated by Django 5.2.8 on 2025-11-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_gainsight_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.JSONField(blank=True, default=list, help_text='List of SurveyMonkey products the customer is using (SME, Audience, MRX, GetFeedback, etc.)'),
        ),
    ]
