# Generated by Django 5.2.8 on 2025-11-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_gainsight_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.JSONField(blank=True, default=list, help_text='Array of SurveyMonkey product names the customer is using (e.g., ["SurveyMonkey Enterprise", "GetFeedback Digital"])'),
        ),
    ]
