"""
Django settings for csmpilot project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    # python-dotenv not installed, skip loading .env
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-@k8%j4$7a0)%inng$$^c9wkagntx$16=y7xdjdghb58xq_2t73')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'on')

ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    '0.0.0.0',
    'testserver',  # For Django tests
    'csmpilot-backend',  # Docker service name
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'django_celery_beat',  # For periodic tasks
    'customers',
    'analytics',
    'integrations',  # Connector/Metadata architecture
    'salesforce',
    'gainsight',
    'gong',  # Gong meetings integration
    # 'mock_apis',  # Removed - using external Node.js service in mock-api-service/
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'csmpilot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'csmpilot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Support both SQLite and PostgreSQL based on DATABASE_URL
DATABASE_URL = os.getenv('DATABASE_URL', 'sqlite:///db.sqlite3')

if DATABASE_URL.startswith('postgresql'):
    # PostgreSQL configuration for Docker/Production
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    # SQLite configuration for local development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Additional directories to search for static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',
] if (BASE_DIR / 'static').exists() else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'PAGE_SIZE_QUERY_PARAM': 'page_size',  # Allow frontend to override page size
    'MAX_PAGE_SIZE': 100,  # Maximum page size allowed
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Spectacular settings for API documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'CSM Copilot API',
    'DESCRIPTION': '''
    A comprehensive Customer Success Management platform API.
    
    ## Features
    - Customer lifecycle management
    - Health score tracking and analytics
    - Feedback and meeting management
    - Risk identification and renewal tracking
    - Industry benchmarking capabilities
    
    ## Authentication
    Currently no authentication required for development.
    
    ## Rate Limiting
    No rate limiting applied in development mode.
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'TAGS': [
        {
            'name': 'customers',
            'description': 'Customer management operations including CRUD and analytics'
        },
        {
            'name': 'feedback', 
            'description': 'Customer feedback tracking and management'
        },
        {
            'name': 'meetings',
            'description': 'Customer meeting records and sentiment tracking'
        }
    ]
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",  # Added for Docker frontend
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",  # Added for Docker frontend
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://192.168.100.28:3000",  # Local network access
]

# Allow all origins for local network (development only)
# For production, use CORS_ALLOWED_ORIGINS above
CORS_ALLOW_ALL_ORIGINS = True  # Set to False in production

CORS_ALLOW_CREDENTIALS = True


# Celery Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Salesforce Mock API Configuration (EXTERNAL service - like real Salesforce)
SALESFORCE_MOCK_API_URL = 'http://localhost:3001/mock-apis/salesforce'
SALESFORCE_SYNC_INTERVAL_HOURS = 1  # Sync every hour

# Gainsight Mock API Configuration (EXTERNAL service - like real Gainsight)
GAINSIGHT_MOCK_API_URL = 'http://localhost:3001/mock-apis/gainsight'
GAINSIGHT_SYNC_INTERVAL_HOURS = 2  # Sync every 2 hours

# Gong Mock API Configuration (EXTERNAL service - like real Gong)
GONG_MOCK_API_URL = 'http://localhost:3001/mock-apis/gong'
GONG_SYNC_INTERVAL_HOURS = 4  # Sync every 4 hours

# OpenAI Configuration for AI Processing
# Set OPENAI_API_KEY in environment variable or .env file
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', None)

# Pinecone Vector Database Configuration
PINECONE_API_KEY = os.getenv('PINECONE_API_KEY')
PINECONE_ENVIRONMENT = os.getenv('PINECONE_ENVIRONMENT', 'us-east-1-aws')
PINECONE_INDEX_NAME = os.getenv('PINECONE_INDEX_NAME', 'csm-copilot')

# Celery Configuration for async tasks
CELERY_BROKER_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# Fix for macOS segmentation faults with ML libraries
# Use threads instead of processes to avoid multiprocessing issues
CELERY_WORKER_POOL = 'threads'
CELERY_WORKER_CONCURRENCY = 2  # Limit concurrent threads
CELERY_WORKER_MAX_TASKS_PER_CHILD = 10  # Restart workers periodically

# Alternative: Use solo pool for development (single-threaded)
# CELERY_WORKER_POOL = 'solo'

# Task routing and execution settings
CELERY_TASK_ROUTES = {
    'customers.tasks.*': {'queue': 'vector_processing'},
}
CELERY_TASK_DEFAULT_QUEUE = 'default'
# Celery Configuration
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# Salesforce Mock API Configuration (EXTERNAL service - like real Salesforce)
SALESFORCE_MOCK_API_URL = 'http://localhost:3001/mock-apis/salesforce'
SALESFORCE_SYNC_INTERVAL_HOURS = 1  # Sync every hour

# Gainsight Mock API Configuration (EXTERNAL service - like real Gainsight)
GAINSIGHT_MOCK_API_URL = 'http://localhost:3001/mock-apis/gainsight'
GAINSIGHT_SYNC_INTERVAL_HOURS = 2  # Sync every 2 hours

# Gong Mock API Configuration (EXTERNAL service - like real Gong)
GONG_MOCK_API_URL = 'http://localhost:3001/mock-apis/gong'
GONG_SYNC_INTERVAL_HOURS = 4  # Sync every 4 hours

# OpenAI Configuration for AI Processing
# Set OPENAI_API_KEY in environment variable or .env file
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', None)
