# Generated by Django 4.2.26 on 2025-11-12 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainsightCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gainsight_id', models.CharField(db_index=True, help_text='Gainsight Company GSID (e.g., 1I0054U9FAKXZ0H26HO92M3F1G5SPWVQDNF3)', max_length=50, unique=True)),
                ('company_name', models.CharField(help_text='Company name from Gainsight', max_length=255)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('churned', 'Churned'), ('at_risk', 'At Risk'), ('expansion', 'Expansion')], help_text='Company status', max_length=50, null=True)),
                ('stage', models.CharField(blank=True, choices=[('new_customer', 'New Customer'), ('kicked_off', 'Kicked Off'), ('launched', 'Launched'), ('adoption', 'Adoption'), ('expansion', 'Expansion'), ('renewal', 'Renewal'), ('churned', 'Churned')], help_text='Current lifecycle stage', max_length=50, null=True)),
                ('csm_name', models.CharField(blank=True, help_text='Customer Success Manager name', max_length=255, null=True)),
                ('csm_email', models.EmailField(blank=True, help_text='Customer Success Manager email', max_length=254, null=True)),
                ('customer_lifetime_in_months', models.IntegerField(blank=True, help_text='Customer lifetime in months', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lifecycle_in_weeks', models.IntegerField(blank=True, help_text='Lifecycle in weeks', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('original_contract_date', models.DateTimeField(blank=True, help_text='Original contract date', null=True)),
                ('renewal_date', models.DateField(blank=True, help_text='Renewal date from Gainsight', null=True)),
                ('employees', models.IntegerField(blank=True, help_text='Number of employees', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('parent_company_id', models.CharField(blank=True, help_text='Parent company Gainsight ID', max_length=50, null=True)),
                ('parent_company_name', models.CharField(blank=True, help_text='Parent company name', max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, help_text='Created date in Gainsight', null=True)),
                ('modified_date', models.DateTimeField(blank=True, help_text='Last modified date in Gainsight', null=True)),
                ('gainsight_metadata', models.JSONField(blank=True, default=dict, help_text='Additional Gainsight metadata')),
                ('raw_api_response', models.JSONField(blank=True, default=dict, help_text='Complete raw API response from Gainsight for RAG processing')),
                ('last_synced_at', models.DateTimeField(auto_now=True, help_text='Last sync timestamp from Gainsight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Link to Customer record', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gainsight_companies', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Gainsight Company',
                'verbose_name_plural': 'Gainsight Companies',
                'ordering': ['-renewal_date', 'company_name'],
                'indexes': [models.Index(fields=['gainsight_id'], name='gainsight_g_gainsig_359f9e_idx'), models.Index(fields=['customer', '-renewal_date'], name='gainsight_g_custome_3bbed4_idx'), models.Index(fields=['status', 'stage'], name='gainsight_g_status_bdfc2f_idx')],
            },
        ),
    ]
